### ISSUE TITLE
SHITEM_URIENTRY uri offset

### ISSUE THREAD

**Issue by zrweger** [williballenthin/shellbags#15]
It seems we're attempting to parse the utf16 uri string beginning at offset 0x7. Based on [libwsi's implementation](https://github.com/libyal/libfwsi/blob/c98ac3c01e24dcfca5ddf9714646fbf8e4ef44b3/libfwsi/libfwsi_uri_values.c), the offset should be 0x8 (note lines 229, 428. It may be helpful to collapse all the ifdef macros).

**Comment by williballenthin** [comment]
nice, thanks for pointing this out. have you encountered data with this type that demonstrates libwsi is correct? i ask not to be defensive, but simply confirm we have a test case (since i don't think i do).

**Comment by zrweger** [comment]
Yes, that's how I stumbled upon this bug. The shell item list in question originated in a jumplist file. I've modified the text portions from the original. Here's the hex encoded shell item list:

6C0061800000000068007400740070003A002F002F00310032003300340035003600370038003900300031003200330034003500360037003800390030003100320033003400350036003700000000001C0000001A00EFBE0200490045002E004800540054005000000050000000

You can verify the bug: [x for x in ShellItems.SHITEMLIST(hex.decode('hex'), 0, None).items()]

UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-33: ordinal not in range(128)

**Comment by williballenthin** [comment]
awesome, thanks for providing the test. parser works as you suggested by changing the offset. i'll push a fix right now.

thanks again for the bug report --- really helpful!
